name: spotipy-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.7,<3.9
  - pip==21.3.1
  - notebook
  - ipywidgets
  - numpy
  - spotipy
  - python-dotenv
  - pip:
      - -r requirements.txt
